site_name: There Hello 的算法知识库
site_url: https://algorithm.therehello.top/
site_author: There Hello

repo_name: therehello/algorithm
repo_url: https://github.com/therehello/algorithm

theme:
  name: material
  language: zh 
  font:
    text: Noto Serif SC
    code: JetBrains Mono
  favicon: https://cdn.jsdelivr.net/gh/removeif/removeif-demo@latest/img/favicon.png
  include_search_page: false
  search_index_only: true
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.code.annotate
    - search.highlight

copyright: '版权所有 © 2022 - 2022 There Hello'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/therehello


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde



extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 首页: 
    - index.md
  - 数据结构:
    - 线段树: ds/seg.md
  - 图论: 
    - 最短路: graph/shortest-path.md
    - 树上问题: 
      - 最近公共祖先: graph/lca.md
      - 树链剖分: graph/hld.md
      - 连通性: 
        - 强连通分量: graph/scc.md
    - 分层最短路: graph/layered-shortest-path.md
    - 差分约束: graph/diff-constraints.md
  - 计算几何:
    - 扫描线: geometry/scanning.md
  - 杂项:
    - 逆序对: misc/count-inversions.md
    - 悬线法: misc/hoverline.md
